# 项目相关配置
boot:
  # 名称
  name: Demo
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2021
  # 文件路径 示例（ Windows配置D:/demo/uploadPath，Linux配置 /home/demo/uploadPath）
#  profile: D:/demo
  profile: /home/data/image
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  port: 18082
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8

spring:
  application:
    name: Upload
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  #文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 50MB
      # 设置总上传的文件大小
      max-request-size: 100MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
logging:
  config: classpath:log/logback-spring.xml

# 开放端点用于SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

