server:
  port: 9002

# Thymeleaf config
spring:
  thymeleaf:
    cache: false
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    encoding: UTF-8
    servlet:
      content-type: text/html


# Payment method parameter configuration
pay:
  alipay:
    app_id: 2021002166664270
    # merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfzFJuNJh/kxOAOFY8zweDC8rE4iREhTLDl0ZcUL1OpabwPU/JjRFuLpgCpHpAsk5TGGG7mboYdS9UH6d7Xg6KZzXJmLo8JKN5plvVgjboBmpW2xAXPT0tH3RjlR26caPHs9GKMkjXrwEz9WI7PF/DDZ6knlwsxnt9ZMlDWmXiXYwSAgeg1UhQXXZtglobOd8TvVEoyM6mEln5Vcr8AOPlJU8uAWcxeY7ZdQy5utwXw+RfUoqjnTCIUMewhjXb8RrZbLX/bAoxYyeGsijc8D1pUd227mjAxNGZYg+RnN+Ri+x54tHD0H1BgP5tqynWcQkrK5Pxg+1WyNhvjYZhZaEDAgMBAAECggEAIeFJLNJ77rh5LvtC1XuzhQZQBHRJ6jkvbSa6pUH9ERqwDUmCjCIbqve4BP9oaCUl1BpcRlEukpbt5PEdKlvjy1ZcohR+j9fYzScHW3pTN9h8XVPu0m6KdPGxVJe+CNSlO+cVKy7EIO6a27BQFm0ThKBznUVyF5AxiIGA5oXZCighO9Pextn3AyCmNUIWndmU9uToECm7UKDzEJFxLpjdwtzjakpM33YijJ1cDvlfPP9SYD0uJnC8NhgTOBx2ehdzL1YxYsDrRlGeyVGBMI/H7mF/BQyW1KW08U+EnRL3Trmw/yOZsRNT9sMPZGpKn5ER3hikhWOQh39amaameVhbgQKBgQD/RkEJpYU40ZWUI+4sV1cl/Cc19TkCr4zvi3S0WSZWd6gLMusNwmXwY937ovriZpCUTLAwDPIi1i3ySTKuio6XGh4Ctk/VPM3Z6Rbuu7vyg1KFynj40tssfzm/kEGn5eUChOMPX80tdgAXG2SAuGD/GOS5wjokho4Q1Gq2yoKcQwKBgQCgQJimrQ2EFHZ2as9ghi4sGo4TAGJH6Yu9o/GsrfsZ0p/hAR3+BNglfh8+Z86eUkB157b2iQ4WnbxMgrp9J/ghRogmsZ+RlhuAOirQQ8lVMcRcdt3BafNqykzBognxULrosFvrNKBWeyzG+owZfMRiAW2MrMDcC/r+kHt7mE78QQKBgCRtWgqOXBxni/i/x9T8Aauh99ZzT9daRbpJJDY4IohkOs6eTXyBKRrMpXirITH9gNQovVud/U+LULMqTtkpXH+jcnTgnzPGoXlfEa6vi3pn0vbUlb6sGCqZXRxA8Z2L6MobPGuNODIsjIa/me/kX7MHUlxPowxjRxKPvUqoS0sRAoGAEG3u+I+fZh4u8v8KWcwH6c+jJ0GP0e2YvQ2U1m5T4xbb+1aA+60Fd/qRO3WrEkI+h5gFAwuUHS94waNZeUFiyA6SIN1vDZ8FHMVZ5FY+yvQ6PHyXSaASK62n5uY0/L+ZGggStG+FzLf+JDxFpstK2v1ofNatQyIbToQDlO1Nk8ECgYEA+2zRLKD9t3/tODZna90B4ZbIgG4hVi97D89Hg6GWxFqkaaFFg8wxg9TTewRp3InN5zYOYyf13X8wQRirMoZDgYLzP6F53gnpXccvWnhtTGlHnicTtnPozC/c/Nw8jn3ywXpO/6i+gE9LI/3u/eA9FPnf4Ckmwcp1/2Poz6V6+Q8=
    # alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAppGjKB4yXUPNf6PtKgfhL9z5JFoP/3VPqgSeG90a9a6/8h2CEvE1j6oLAVVnZDNQFGa6RH3jomgQTld10ckWhshKwmuLBsAzSRRmy2Rp15ru9SNbK7QnfeQZXwiITltp2BrTFG+H2U6Wy3MQ1VyOg6lrmM8TvlzRa+NoJN037meznW+pd3k/usS+qvY1OWZjCt041b0wFSjydsRdZKKDgzqaAqy8FTdNbMB/0GONTaM4eWjJc+Eww8r8rRblV44vP53kiFGlcKY7OxrmJ/5ESKkQ2EW4/liYU5mGyY2U9qoj7JRFPxlNsXQIFqAHuS48oqDoq/7GkB9/e5Mqq1o0rQIDAQAB
    # 应用私钥
    app_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCJSR0AQaazBjDwbEJH0M7JKpE79F/L7p6w2mIjevelQrPfESAy9rHD/j0tZgOpwA/UQfTkFeDTz7uA34k2KPCK2ygZr0I3Wsjf+PozJ1BLZ7JGiYCNHYbbQ48scNaFiN8zhayIgwd5m+b7aP14HcPZEIfyPGGRjXoCmQ+kQVZcZBcu/XWc/RixgSGqJUbU2/yyP8baI7610LDpzGk7ZCpUse2pQw2UQOj7dzClLa3TdSd+v/EyVBje671XdMMuZcBCJOhOeASNbIATWXjS4DygcjZP3bYDu5VEkahaeP5LATNOdldznpiqoY8tjNs/T/DwyMPjyXPzhyjEvoSXSJuXAgMBAAECggEAPiO53MPakG3c+PYHijoZXzTFSD30nnoDmkk+4pBmR4dJo049JNRE4lHRnxrtzYgBojG4hwTgHv+H/20uzjT5q+BG5llNv4B4K+imV0EUNw1YxFS4uycCQ3zw8UyhzQ+G9+spjSDB4WmPw3xiPlw6qaWx4xMxlpBTCZn+Wnq4fFijT+M+hl8KvBsdpqYHqg4bg/wzkBsO9bjZxXcV41zzouyYjBLPuBTr9RpxqQaig3RchtVnfTv0mYOUR+ozd+ib9pFKUuTZZhvT8ioP5DvpVgniakAkKRpNBJ8IXx1ZC6gw3Ek50HmPQk6BDBgYJX0FFzg0svn9eWvZnsgxtB+lAQKBgQDsooP9EOFSs0Agb+8TTSJ2M6BTQzLZLu3aC4NoPJAw1i/pApTvFPcJ37IaIJ3J1L/THMaxAuyM+dpA8KhBdPqROQMFQuvu4e/S/DJ3mY6IaNJUN15NyzoLzK5YQ9or5ofiiju9ix5faNGmKy8qVxLcLFUqmINocPR1IZNB00qncwKBgQCUhTzeF1BfTbzHN/h+gbzKjMdKnJ06cHMjGleuMgf4Y/6a8flFV3tE7MR6Lnd9LS6QWc9tUIOPk2R9ruO+dhHQCzouZoyH58hlKw2Ukd1S2qtFVuNApm5Kg2H1P3FSuqACBbrTIKuVQQDC8iG6UUXTsfjhjSYlBn80ydDQd59KTQKBgGL6BuMO8HA68ZOfvgwAs21lYqXw8Y/OBUaykiBDVLxYmmmH3uuxhTLoEgLDqbwF9MZEvwbDBlZhG10WTAo096lOg2jr+OtOLZW+Tw2fePKthWwcTKGVY44T6siYeOTr4+Jpl1tMmUOnACnU3kGDciwNjwHmEPDabiWgCYv66LrpAoGBAIiODM3iv7owvo6pTqf6X3wYfjCC2SlfNO2kjdOTGrLuNa1/KALykVtpGqmAScrlHPgKK2bF7YC4M2A/yhRXeL9BY2hAT5uxqBYkxKLCjq1ccrcZUW8i1ytZq1qTz30SLIZPgFwYoMplbu7PM+WcTkh7TWsMnXLTi2gc2wqhwerNAoGBALMA3DwvBjXOUhxY15tGSuOFFbMpPypkCANrcg30BQh2xG0EAhlft6sCvsVKodDjr/64pd5b2gbUOg690bsBaNP1yza4CHtSmnPrAx3t3Vpla4+R7SdWXZhW8byl/c0uM9snmJmmUV6xdpWzw7jzdNCs65v8fM8mmgWdx4mEmIfV
    # 应用公钥证书
    app_certPath: E:\b-wordplace\example\bootDemo\pay-demo-01\pay-demo-02\companyCert\appCertPublicKey_2021002166664270.crt
    # 支付宝根证书
    ali_rootCertPath: E:\b-wordplace\example\bootDemo\pay-demo-01\pay-demo-02\companyCert\alipayRootCert.crt
    # 支付宝公钥证书
    ali_public_CertPath: E:\b-wordplace\example\bootDemo\pay-demo-01\pay-demo-02\companyCert\alipayCertPublicKey_RSA2.crt
    # 后台回调地址
    notify_url: http://h89zsg.natappfree.cc/pay/alipay/notify
    protocol: https
    sign_type: RSA2
    gateway_url: openapi.alipay.com
    encrypt_key: 42Wl4JJb70wSn633AJLEmg==
  #  return_url: https://cloud.xmlcitc.com/pay/alipay/return\
  # 前台跳转地址
  return_url: http://h89zsg.natappfree.cc/pay/alipay/return

  wechatpay:
    # 绑定的商家appId
    app_id: wx18463c67dbbfe80c
    # 商户私钥路径
    api_client_key_pem: C:\wechatpay\apiclient_key.pem
    # 平台证书路径
    platform_cert_pem: C:\wechatpay\wechatpay_73791C6455DD3EC12FE95E4051F71A1EE688A860.pem
    # 商户号
    mch_id: 1567964681
    # API证书序列号
    mch_serial_no: 23D837D84A7DAE38F30D57197F5745BEC59E28FF
    # apiV3 密钥
    api_v3: 9Cl7J0PzUAEJzKEXSaRXnszFSUnQX31V
    # 扫码页面路径
    pay_page_url: https://cloud.xmlcitc.com/wechatpay/scan
    # 回调地址，注意 notify结尾处不能携带其他内容
    notify_url: https://cloud.xmlcitc.com/v1/pay/wechatpay/notify

