server:
  port: 9002

# Thymeleaf config
spring:
  thymeleaf:
    cache: false
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    encoding: UTF-8
    servlet:
      content-type: text/html


# Payment method parameter configuration
pay:
  alipay:
    app_id: 2021000117627663
    # merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfzFJuNJh/kxOAOFY8zweDC8rE4iREhTLDl0ZcUL1OpabwPU/JjRFuLpgCpHpAsk5TGGG7mboYdS9UH6d7Xg6KZzXJmLo8JKN5plvVgjboBmpW2xAXPT0tH3RjlR26caPHs9GKMkjXrwEz9WI7PF/DDZ6knlwsxnt9ZMlDWmXiXYwSAgeg1UhQXXZtglobOd8TvVEoyM6mEln5Vcr8AOPlJU8uAWcxeY7ZdQy5utwXw+RfUoqjnTCIUMewhjXb8RrZbLX/bAoxYyeGsijc8D1pUd227mjAxNGZYg+RnN+Ri+x54tHD0H1BgP5tqynWcQkrK5Pxg+1WyNhvjYZhZaEDAgMBAAECggEAIeFJLNJ77rh5LvtC1XuzhQZQBHRJ6jkvbSa6pUH9ERqwDUmCjCIbqve4BP9oaCUl1BpcRlEukpbt5PEdKlvjy1ZcohR+j9fYzScHW3pTN9h8XVPu0m6KdPGxVJe+CNSlO+cVKy7EIO6a27BQFm0ThKBznUVyF5AxiIGA5oXZCighO9Pextn3AyCmNUIWndmU9uToECm7UKDzEJFxLpjdwtzjakpM33YijJ1cDvlfPP9SYD0uJnC8NhgTOBx2ehdzL1YxYsDrRlGeyVGBMI/H7mF/BQyW1KW08U+EnRL3Trmw/yOZsRNT9sMPZGpKn5ER3hikhWOQh39amaameVhbgQKBgQD/RkEJpYU40ZWUI+4sV1cl/Cc19TkCr4zvi3S0WSZWd6gLMusNwmXwY937ovriZpCUTLAwDPIi1i3ySTKuio6XGh4Ctk/VPM3Z6Rbuu7vyg1KFynj40tssfzm/kEGn5eUChOMPX80tdgAXG2SAuGD/GOS5wjokho4Q1Gq2yoKcQwKBgQCgQJimrQ2EFHZ2as9ghi4sGo4TAGJH6Yu9o/GsrfsZ0p/hAR3+BNglfh8+Z86eUkB157b2iQ4WnbxMgrp9J/ghRogmsZ+RlhuAOirQQ8lVMcRcdt3BafNqykzBognxULrosFvrNKBWeyzG+owZfMRiAW2MrMDcC/r+kHt7mE78QQKBgCRtWgqOXBxni/i/x9T8Aauh99ZzT9daRbpJJDY4IohkOs6eTXyBKRrMpXirITH9gNQovVud/U+LULMqTtkpXH+jcnTgnzPGoXlfEa6vi3pn0vbUlb6sGCqZXRxA8Z2L6MobPGuNODIsjIa/me/kX7MHUlxPowxjRxKPvUqoS0sRAoGAEG3u+I+fZh4u8v8KWcwH6c+jJ0GP0e2YvQ2U1m5T4xbb+1aA+60Fd/qRO3WrEkI+h5gFAwuUHS94waNZeUFiyA6SIN1vDZ8FHMVZ5FY+yvQ6PHyXSaASK62n5uY0/L+ZGggStG+FzLf+JDxFpstK2v1ofNatQyIbToQDlO1Nk8ECgYEA+2zRLKD9t3/tODZna90B4ZbIgG4hVi97D89Hg6GWxFqkaaFFg8wxg9TTewRp3InN5zYOYyf13X8wQRirMoZDgYLzP6F53gnpXccvWnhtTGlHnicTtnPozC/c/Nw8jn3ywXpO/6i+gE9LI/3u/eA9FPnf4Ckmwcp1/2Poz6V6+Q8=
    # alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAppGjKB4yXUPNf6PtKgfhL9z5JFoP/3VPqgSeG90a9a6/8h2CEvE1j6oLAVVnZDNQFGa6RH3jomgQTld10ckWhshKwmuLBsAzSRRmy2Rp15ru9SNbK7QnfeQZXwiITltp2BrTFG+H2U6Wy3MQ1VyOg6lrmM8TvlzRa+NoJN037meznW+pd3k/usS+qvY1OWZjCt041b0wFSjydsRdZKKDgzqaAqy8FTdNbMB/0GONTaM4eWjJc+Eww8r8rRblV44vP53kiFGlcKY7OxrmJ/5ESKkQ2EW4/liYU5mGyY2U9qoj7JRFPxlNsXQIFqAHuS48oqDoq/7GkB9/e5Mqq1o0rQIDAQAB
    # 应用私钥
#    app_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCMFkcr0J2gOTXwLdDmmjYuiDTpcTclxp6ahBb43UOkQVxdhFuHU65tpzl9OaS6MXhzRZl01t3E5WH1TRaI1UjsrmlLfi2Kin6SSiX2mHF9OhaAxn2FrVQLn4zASH5MXTRNavp9YXYzIY7X3/V4+M7vsuYuWcre717TCrweOqUSxcGhxsxkY2BRPoqXnInrcWDarIAV/2F8mAPxGPidGgIETFHbGebcPdI731Y+0XLWdP4Cgrp4aHumH2hUuNBo7uH3WmRDt70ogw1WFBcsbtxvu0FnfBMTIYoV2D5ultpPIOHqOi8sohD2yW5FL6qghxGT1JIvYtxNtoeb+hBW8T0NAgMBAAECggEAU8hPMKlIXLdaxxbfxcuddB8KZkPME8/Cs+8kPhs3hVmCAHxUsY8e134YKAj9uE42F9sceIC5ijUWbTt5qsTFJKj7WKdSXXWPVbb7FYz+80J2ivYrxHNxvLHj4Gx6/PkReuvsfGh55QLBB+NuULeeLEX23OnfJ45KTDYzZHD2oU649hjn2hifui9SjaapnnUS/AKnibRRnee5JVhMQH6ZcwVyTV/Mjsp+lvSqxOLBA3sXw1nC7rszzw8Y2sDI2yygkrrsWtTzMcVceGuMreXGbzjTpbtQl2C7eNYGoMyZadj9jx/NAMpYezNcoKFX1ah0mkFmzb3zQQDFoISIJXEOEQKBgQDU+Nv1XYe7FfvxiSy2P2BJaBQS9r9jDP6blBmeohdhlHR3nqldBjjwX35f0wpUI+NjvesDSNwVKCyN0qIxM1rdvISWcU4lGJDjJTBf81rENI86OmCQPuSPfGVVF9NtqbfDS1agXKNtJ9rUG9/x/l8jtEt2YAxZySlHQgKa2BHV7wKBgQCoY7nRBke2j2pUUJqSgj+924eACMiHNmcSHgbJZiF3v98h+7122i3dEgtq7crlSTtKSHL+r9xuXfPYzEXiggK11SIlxhKpmcCXQG8PVWHQkD18q5X/HWE/gdkdzkpzXtS7mxDU9F13OpGLsCgIvVL+p2fe3Zjp0sUrBmDX5WE4wwKBgQCWWfYXO+eFyZhrRXdeVlGooSSC2tX0nIjm1uBbYH13MzIh/M3+UVVDRXdXOQsyqX9vu/U9BWPyP8FsgkZky6eboOpNt0H+6F/pLCkBpDDxEVYIOoxPaUc8kQqMz1xBMC7+XaKTZbMubZOMaP1pvzX1Y+RedqJhhKVynARwwpec2wKBgEhgfPjcEyzj3dcZwiag91baqhYdMFv1xT2jTFV6oX4AKZ9Ivfn882OnIuM2DFSbMnHOTCcuXbfOiEYyHwOp0BJp5sCHr3PYk1AvsMzNbTqhFNymP9Wkwizy2eiWx6dpJlTw5L4zvozFztNUxxBil+6+88V2SAiQwJCqsCt7+1rTAoGBAK1piJgik5ocjZkXryWYfeVEzkz3sug/IOd1ONngytKXalGe4G+IWQoQm+uNHFCKuRyA2f+XNZhMsk/E4N0jZdUuJ3LhODNpaHazZWjQB9n5OOtV/jdwtay98ds5VFJrrNBIeOZhipiNlHWsLaO1a8RJp1FYXigwECuL4G7Dl6bn
    app_private_key: static/ali/private_key.txt
    # 应用公钥证书
    app_certPath: static/ali/appCertPublicKey_2021000117627663.crt
    # 支付宝根证书
    ali_rootCertPath: static/ali/alipayRootCert.crt
    # 支付宝公钥证书
    ali_public_CertPath: static/ali/alipayCertPublicKey_RSA2.crt
    # 后台回调地址
    notify_url: https://ennfq8.natappfree.cc/pay/alipay/notify
    protocol: https
    sign_type: RSA2
    gateway_url: openapi.alipaydev.com
    encrypt_key: ylHgosQjbzsaYoQSD1eJNQ==
  #  return_url: https://cloud.xmlcitc.com/pay/alipay/return\
  # 前台跳转地址
  return_url:  https://ennfq8.natappfree.cc/pay/alipay/return

  wechatpay:
    # 绑定的商家appId
    app_id: wx18463c67dbbfe80c
    # 商户私钥路径
    api_client_key_pem: C:\wechatpay\apiclient_key.pem
    # 平台证书路径
    platform_cert_pem: C:\wechatpay\wechatpay_73791C6455DD3EC12FE95E4051F71A1EE688A860.pem
    # 商户号
    mch_id: 1567964681
    # API证书序列号
    mch_serial_no: 23D837D84A7DAE38F30D57197F5745BEC59E28FF
    # apiV3 密钥
    api_v3: 9Cl7J0PzUAEJzKEXSaRXnszFSUnQX31V
    # 扫码页面路径
    pay_page_url: https://cloud.xmlcitc.com/wechatpay/scan
    # 回调地址，注意 notify结尾处不能携带其他内容
    notify_url: https://cloud.xmlcitc.com/v1/pay/wechatpay/notify

