server:
  port: 18083

spring:
  application:
    name: Quartz
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  profiles:
    active: druid

#  mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    #控制台打印sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# 开放端点用于SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

